server:
  port: 18888

spring:
  application:
    name: ts-assurance-service
  data:
    mongodb:
      host: ts-assurance-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: assurance.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,bean'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true