---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: hotrod
  name: hotrod
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: hotrod

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hotrod
spec:
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - image: mikelorant/jaeger-hotrod
        name: hotrod
        ports:
        - containerPort: 8080
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector.kube-system:14267"