apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-execute-service
spec:
  selector:
    matchLabels:
      app: ts-execute-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-execute-service
    spec:
      containers:
      - name: ts-execute-service
        image: kanakami/ts-execute-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12386
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12386
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
spec:
  ports:
    - name: http
      port: 12386
  selector:
   app: ts-execute-service

---