#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ts-execute-service
#spec:
#  selector:
#    matchLabels:
#      app: ts-execute-service
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: ts-execute-service
#    spec:
#      containers:
#      - name: ts-execute-service
#        image: kanakami/ts-execute-service:0.0.1
#        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 12386
#        resources:
#          requests:
#            cpu: 50m
#            memory: 160Mi
#          limits:
#            cpu: 200m
#            memory: 500Mi
#        readinessProbe:
#          tcpSocket:
#            port: 12386
#          initialDelaySeconds: 160
#          periodSeconds: 10
#          timeoutSeconds: 5
#      volumes:
#      - name: date-config
#        hostPath:
#          path: /etc/localtime
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: ts-execute-service
#spec:
#  ports:
#    - name: http
#      port: 12386
#  selector:
#   app: ts-execute-service
#
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel-plan-service
spec:
  selector:
    matchLabels:
      app: ts-travel-plan-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-plan-service
    spec:
      containers:
        - name: ts-travel-plan-service
          image: kanakami/ts-travel-plan-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 14322
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              cpu: 200m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 14322
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
spec:
  ports:
    - name: http
      port: 14322
  selector:
    app: ts-travel-plan-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  selector:
    matchLabels:
      app: ts-basic-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
      - name: ts-basic-service
        image: kanakami/ts-basic-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15680
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 15680
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - name: http
      port: 15680
  selector:
   app: ts-basic-service

---