spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
#      host: localhost
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,bean'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true