server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
#      host: localhost
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,bean'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true