server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,bean'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true