spring:
  application:
    name: ts-route-plan-service

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,bean'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true